// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTNHmB3yUsiARgFSnt90tbhE_Xl9Uu4_c',
    appId: '1:89696239203:web:f2a72edbbc4934b699c256',
    messagingSenderId: '89696239203',
    projectId: 'team-33-app',
    authDomain: 'team-33-app.firebaseapp.com',
    storageBucket: 'team-33-app.appspot.com',
    measurementId: 'G-0GSLXS59FJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP0FuCaxl28HxsgzjIKs1RYDz-b97IUVU',
    appId: '1:89696239203:android:2f5f4eaa544ded7199c256',
    messagingSenderId: '89696239203',
    projectId: 'team-33-app',
    storageBucket: 'team-33-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNjkn7av0LUIllp9uoxck_UDf4hIn7Z3o',
    appId: '1:89696239203:ios:e6ba2000c1139c1199c256',
    messagingSenderId: '89696239203',
    projectId: 'team-33-app',
    storageBucket: 'team-33-app.appspot.com',
    iosClientId: '89696239203-29bq18gp1fe6k042okahjelm6ueim29i.apps.googleusercontent.com',
    iosBundleId: 'com.example.team33App',
  );
}
